name: "Validate - Hassfest & Hacs"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - "custom_components/**"
  pull_request:
    paths:
      - "custom_components/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set_condition:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Step
        run: |
          # Your commands here
          echo "Running conditional job"

          # Set an environment variable based on the secret
          if [ -n "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "DISCORD_WEBHOOK is set"
            echo "::set-env name=DISCORD_WEBHOOK_FLAG::true" # Set an environment variable
          else
            echo "DISCORD_WEBHOOK is not set"
            echo "::set-env name=DISCORD_WEBHOOK_FLAG::false" # Set an environment variable
          fi

  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: "Validate Hassfest"
    if: ${{ env.DISCORD_WEBHOOK_FLAG == 'true' }}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Run hassfest validation"
        uses: "home-assistant/actions/hassfest@master"

  hacs: # https://github.com/hacs/action
    name: "Validate HACS"
    if: ${{ env.DISCORD_WEBHOOK_FLAG == 'true' }}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Run HACS validation"
        uses: "hacs/action@main"
        with:
          category: "integration"
